### PR TITLE
feat: `at_directory_connection`

### LINKED ISSUE #4: Talking to atDirectory
## Description

Create a class `AtRootConnection` that establishes a connection to the root server given an address (such as `root.atsign.org:64`)

## Starting Points

- Class `AtRootConnection`
- Take in constructor `root.atsign.org:64`
- `.executeCommand(std::string)` method (returns std::string which is the response)
- Consult resources [here](https://github.com/atsign-labs/at_cpp/blob/trunk/lib/AtClient.cpp)

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
## What I did

- working `at_root_connection`

closes #4

### CODE REVIEW

**Review by TylerTrott — CHANGES_REQUESTED** [review]
Are we going to leave the const char certificate hard coded? Thought it was supposed to be dynamic

**Comment by JeremyTubongbanua** [comment]
> Are we going to leave the const char certificate hard coded? Thought it was supposed to be dynamic

This is one of the things I will speak to Gary about

**Comment by TylerTrott** [comment]
> > Are we going to leave the const char certificate hard coded? Thought it was supposed to be dynamic
> 
> This is one of the things I will speak to Gary about

Okay, do we wanna wait on this merge then?

**Comment by JeremyTubongbanua** [comment]
> > > Are we going to leave the const char certificate hard coded? Thought it was supposed to be dynamic
> > 
> > 
> > This is one of the things I will speak to Gary about
> 
> Okay, do we wanna wait on this merge then?

Merge for now (cause it works) and will refactor later. I will write a ticket on it

**Comment by JeremyTubongbanua** [comment]
See #12

**Review by TylerTrott — APPROVED** [review]
To be updated

**Pull request merged**
